export interface Bar {
  name: string;
  city: string;
  country: string;
  address: string;
  description: string;
  instagram: string;
  instagram_url: string;
  website: string;
  phone: string;
  gradient: string;
  ranking_badge: string;
  rankings: string;
}

export const BARS_DATA: Bar[] = [
  {
    "name": "Bar Leone",
    "city": "Hong Kong",
    "country": "China",
    "address": "11-15 Bridges Street, Central, Hong Kong",
    "description": "Bar Leone is an Italian-inspired neighborhood cocktail bar known for 'cocktail popolari'—accessible, classic drinks in a convivial,...",
    "instagram": "@barleonehk",
    "instagram_url": "https://www.instagram.com/barleonehk",
    "website": "https://www.barleonehk.com",
    "phone": "Not listed",
    "gradient": "linear-gradient(135deg, hsl(5, 30%, 15%), hsl(45, 25%, 10%))",
    "ranking_badge": "#1 World's Best",
    "rankings": "World's 50 Best Bars 2025 #1; Asia's 50 Best Bars 2025 #1; Top 500 Bars 2025 #3; Spirited Awards 2025: Best International Cocktail Bar"
  },
  {
    "name": "Handshake Speakeasy",
    "city": "Mexico City",
    "country": "Mexico",
    "address": "Amberes 65, Col. Juárez, Cuauhtémoc, CDMX 06600",
    "description": "Handshake Speakeasy is a renowned speakeasy-style cocktail bar known for its innovative, high-end cocktails, sophisticated ambiance...",
    "instagram": "@handshake_bar",
    "instagram_url": "https://www.instagram.com/handshake_bar",
    "website": "https://handshake.bar",
    "phone": "+52 55 5200 0000",
    "gradient": "linear-gradient(135deg, hsl(165, 30%, 15%), hsl(205, 25%, 10%))",
    "ranking_badge": "#2 World's Best",
    "rankings": "World's 50 Best Bars 2025 #2; North America's 50 Best Bars 2025 #1; Top 500 Bars 2025 #4"
  },
  {
    "name": "Sips",
    "city": "Barcelona",
    "country": "Spain",
    "address": "C/ Muntaner 108 (Tienda 2), 08036 Barcelona",
    "description": "Sips is a world-renowned cocktail bar known for its innovative mixology, exceptional service, and unique flavor experiences using local...",
    "instagram": "@sips.drinkeryhouse",
    "instagram_url": "https://www.instagram.com/sips.drinkeryhouse",
    "website": "https://sips.barcelona/",
    "phone": "+34 619 64 14 02",
    "gradient": "linear-gradient(135deg, hsl(322, 30%, 15%), hsl(2, 25%, 10%))",
    "ranking_badge": "#3 World's Best",
    "rankings": "World's 50 Best Bars 2025 #3; Top 500 Bars 2025 #10"
  },
  {
    "name": "Paradiso",
    "city": "Barcelona",
    "country": "Spain",
    "address": "Carrer de Rera Palau, 4, 08003 Barcelona",
    "description": "World-renowned speakeasy cocktail bar hidden behind a fridge door in a pastrami shop in El Born, known for inventive, theatrical...",
    "instagram": "@paradiso_barcelona",
    "instagram_url": "https://www.instagram.com/paradiso_barcelona",
    "website": "https://paradiso.cat/en/",
    "phone": "+34 933 607 222",
    "gradient": "linear-gradient(135deg, hsl(155, 30%, 15%), hsl(195, 25%, 10%))",
    "ranking_badge": "#4 World's Best",
    "rankings": "World's 50 Best Bars 2025 #4; Top 500 Bars 2025 #2"
  },
  {
    "name": "Connaught Bar",
    "city": "London",
    "country": "United Kingdom",
    "address": "The Connaught, Carlos Place, Mayfair, London W1K 2AL",
    "description": "The Connaught Bar is an award-winning luxury cocktail bar in Mayfair, renowned for its innovative and classic cocktails, world-class...",
    "instagram": "@theconnaught",
    "instagram_url": "https://www.instagram.com/theconnaught",
    "website": "https://www.maybourne.com/en/hotels/the-connaught/restaurants-bars/connaught-bar",
    "phone": "+44 (0)20 7499 7070",
    "gradient": "linear-gradient(135deg, hsl(121, 30%, 15%), hsl(161, 25%, 10%))",
    "ranking_badge": "#6 World's Best",
    "rankings": "World's 50 Best Bars 2025 #6; Top 500 Bars 2025 #12"
  },
  {
    "name": "Moebius Milano",
    "city": "Milan",
    "country": "Italy",
    "address": "Via Alfredo Cappellini, 25, 20124 Milano MI",
    "description": "Moebius Milano is a multifaceted cultural hub in a former textile warehouse, featuring a cocktail bar, tapa bistrot, Michelin-starred...",
    "instagram": "@moebiusmilano",
    "instagram_url": "https://www.instagram.com/moebiusmilano",
    "website": "https://moebiusmilano.it/",
    "phone": "+39 02 3664 3680",
    "gradient": "linear-gradient(135deg, hsl(356, 30%, 15%), hsl(36, 25%, 10%))",
    "ranking_badge": "#7 World's Best",
    "rankings": "World's 50 Best Bars 2025 #7; Spirited Awards 2025: Best International Restaurant Bar"
  },
  {
    "name": "Line",
    "city": "Athens",
    "country": "Greece",
    "address": "Agathodemonos 37, Orestou 1, 118 53",
    "description": "An airy former art gallery turned innovative cocktail bar known for its farm-to-glass ethos, in-house fermented fruit wines (Why-ins),...",
    "instagram": "@line",
    "instagram_url": "https://www.instagram.com/line.athens",
    "website": "https://lineathens.gr/",
    "phone": "+30 211 750 7185",
    "gradient": "linear-gradient(135deg, hsl(39, 30%, 15%), hsl(79, 25%, 10%))",
    "ranking_badge": "#8 World's Best",
    "rankings": "World's 50 Best Bars 2025 #8; Top 500 Bars 2025 #120"
  },
  {
    "name": "Jigger & Pony",
    "city": "Singapore",
    "country": "Singapore",
    "address": "165 Tanjong Pagar Road, Singapore 088539, Amara Singapore",
    "description": "Singapore's iconic cocktail bar, rooted in classic cocktails with a contemporary twist and renowned for convivial hospitality. Ranked...",
    "instagram": "@jiggerandponysg",
    "instagram_url": "https://www.instagram.com/jiggerandponysg",
    "website": "https://www.jiggerandpony.com](https://www.jiggerandpony.com",
    "phone": "+65 9621 1074",
    "gradient": "linear-gradient(135deg, hsl(277, 30%, 15%), hsl(317, 25%, 10%))",
    "ranking_badge": "#9 World's Best",
    "rankings": "World's 50 Best Bars 2025 #9; Asia's 50 Best Bars 2025 #3; Top 500 Bars 2025 #5"
  },
  {
    "name": "Tres Monos",
    "city": "Buenos Aires",
    "country": "Argentina",
    "address": "Guatemala 4899, C1425 Buenos Aires, Argentina",
    "description": "A dark and divey rock bar in Palermo showcasing Argentina's liquid larder with creative cocktails, local-sourced products like house...",
    "instagram": "@3monosbar",
    "instagram_url": "https://www.instagram.com/3monosbar",
    "website": "https://3monos.com.ar/bar/",
    "phone": "+54 9 11 2896-9457",
    "gradient": "linear-gradient(135deg, hsl(64, 30%, 15%), hsl(104, 25%, 10%))",
    "ranking_badge": "#10 World's Best",
    "rankings": "World's 50 Best Bars 2025 #10; Top 500 Bars 2025 #13"
  },
  {
    "name": "Alquímico",
    "city": "Cartagena",
    "country": "Colombia",
    "address": "Cl. del Colegio #34-24, Centro Histórico, Cartagena de Indias",
    "description": "Award-winning multi-level cocktail bar in a historic colonial house, celebrating Colombian biodiversity through innovative, sustainable...",
    "instagram": "@alquimicocartagena",
    "instagram_url": "https://www.instagram.com/alquimicocartagena",
    "website": "https://alquimico.com",
    "phone": "+57 318 8450433",
    "gradient": "linear-gradient(135deg, hsl(189, 30%, 15%), hsl(229, 25%, 10%))",
    "ranking_badge": "#11 World's Best",
    "rankings": "World's 50 Best Bars 2025 #11"
  },
  {
    "name": "Superbueno",
    "city": "New York",
    "country": "USA",
    "address": "13 1st Avenue, East Village, New York, NY 10003",
    "description": "Mexican-American cocktail bar in NYC's East Village known for vibrant, energetic vibes blending Mexican flavors with NYC cocktail...",
    "instagram": "@superbuenonyc",
    "instagram_url": "https://www.instagram.com/superbuenonyc",
    "website": "https://www.superbuenonyc.com",
    "phone": "347-866-7739",
    "gradient": "linear-gradient(135deg, hsl(233, 30%, 15%), hsl(273, 25%, 10%))",
    "ranking_badge": "#12 World's Best",
    "rankings": "World's 50 Best Bars 2025 #12; North America's 50 Best Bars 2025 #2; Top 500 Bars 2025 #35"
  },
  {
    "name": "Lady Bee",
    "city": "Lima",
    "country": "Peru",
    "address": "Pedro de Osma 205, Barranco, Lima, Peru",
    "description": "Cocktail bar and eatery renowned for product-driven mixology using native Peruvian ingredients from diverse regions, sustainability...",
    "instagram": "@ladybee.lima",
    "instagram_url": "https://www.instagram.com/ladybee.lima",
    "website": "https://ladybee.bar/en/",
    "phone": "+51 1 4383775",
    "gradient": "linear-gradient(135deg, hsl(55, 30%, 15%), hsl(95, 25%, 10%))",
    "ranking_badge": "#13 World's Best",
    "rankings": "World's 50 Best Bars 2025 #13; Top 500 Bars 2025 #44"
  },
  {
    "name": "Himkok",
    "city": "Oslo",
    "country": "Norway",
    "address": "Storgata 27, 0184 Oslo",
    "description": "Himkok is a renowned cocktail bar and on-site distillery in Oslo, known for expertly crafted cocktails and spirits like aquavit, gin,...",
    "instagram": "@himkok",
    "instagram_url": "https://www.instagram.com/himkok.oslo",
    "website": "https://www.himkok.no",
    "phone": "+47 22 42 22 02",
    "gradient": "linear-gradient(135deg, hsl(142, 30%, 15%), hsl(182, 25%, 10%))",
    "ranking_badge": "#14 World's Best",
    "rankings": "World's 50 Best Bars 2025 #14; Top 500 Bars 2025 #6"
  },
  {
    "name": "Bar Us",
    "city": "Bangkok",
    "country": "Thailand",
    "address": "61/37 Floor 1, Sukhumvit 26 (Soi Sukhumvit 26), Khlong Tan Nuea, Khlong Toei, Bangkok 10110",
    "description": "High-concept drinking room offering immersive multi-course cocktails structured like fine dining (Starters, Mains, Afters, All Night)...",
    "instagram": "@bar.us.bkk",
    "instagram_url": "https://www.instagram.com/bar.us.bkk",
    "website": "https://www.us-bar.com",
    "phone": "+66 91 721 8209",
    "gradient": "linear-gradient(135deg, hsl(237, 30%, 15%), hsl(277, 25%, 10%))",
    "ranking_badge": "#15 World's Best",
    "rankings": "World's 50 Best Bars 2025 #15; Asia's 50 Best Bars 2025 #4; Top 500 Bars 2025 #30"
  },
  {
    "name": "Zest",
    "city": "Seoul",
    "country": "South Korea",
    "address": "B1, 26 Dosan-daero 55-gil, Gangnam-gu, Seoul, South Korea",
    "description": "Zest is a minimalist cocktail bar renowned for sustainable, hyper-seasonal drinks using local Korean ingredients from contract farming...",
    "instagram": "@zest.seoul",
    "instagram_url": "https://www.instagram.com/zest.seoul",
    "website": "",
    "phone": "+82 10 3177 8801",
    "gradient": "linear-gradient(135deg, hsl(200, 30%, 15%), hsl(240, 25%, 10%))",
    "ranking_badge": "#16 World's Best",
    "rankings": "World's 50 Best Bars 2025 #16; Asia's 50 Best Bars 2025 #2; Top 500 Bars 2025 #25"
  },
  {
    "name": "Bar Nouveau",
    "city": "Paris",
    "country": "France",
    "address": "5 Rue des Haudriettes, 75003 Paris",
    "description": "Art Nouveau-inspired cocktail bar over two floors in Paris's Marais district, featuring vintage spirits, delicate cocktails, and elegant...",
    "instagram": "@bar_nouveau_",
    "instagram_url": "https://www.instagram.com/bar_nouveau_",
    "website": "",
    "phone": "",
    "gradient": "linear-gradient(135deg, hsl(291, 30%, 15%), hsl(331, 25%, 10%))",
    "ranking_badge": "#17 World's Best",
    "rankings": "World's 50 Best Bars 2025 #17; Top 500 Bars 2025 #18"
  },
  {
    "name": "Bar Benfiddich",
    "city": "Tokyo",
    "country": "Japan",
    "address": "9F, Yamatoya Bldg., 1-13-7 Nishishinjuku, Shinjuku-ku, Tokyo 160-0023",
    "description": "Tiny 15-seat cocktail bar renowned for inventive, no-menu cocktails crafted on the spot by owner-bartender Hiroyasu Kayama using fresh...",
    "instagram": "@benfiddich_tokyo",
    "instagram_url": "https://www.instagram.com/benfiddich_tokyo",
    "website": "https://benfiddich.tokyo",
    "phone": "+81 3-6258-0309",
    "gradient": "linear-gradient(135deg, hsl(179, 30%, 15%), hsl(219, 25%, 10%))",
    "ranking_badge": "#18 World's Best",
    "rankings": "World's 50 Best Bars 2025 #18; Asia's 50 Best Bars 2025 #9; Top 500 Bars 2025 #42"
  },
  {
    "name": "Caretaker's Cottage",
    "city": "Melbourne",
    "country": "Australia",
    "address": "139-141 Little Lonsdale Street, Behind Wesley Church, Melbourne, Victoria 3000",
    "description": "Caretaker's Cottage is a tiny, trendy cocktail bar housed in a historic stone cottage, known for its exceptional martinis, Guinness,...",
    "instagram": "@caretakers",
    "instagram_url": "https://www.instagram.com/caretakers.cottage",
    "website": "https://www.caretakerscottage.bar",
    "phone": "Not listed",
    "gradient": "linear-gradient(135deg, hsl(150, 30%, 15%), hsl(190, 25%, 10%))",
    "ranking_badge": "#19 World's Best",
    "rankings": "World's 50 Best Bars 2025 #19; Top 500 Bars 2025 #47"
  },
  {
    "name": "The Cambridge Public House",
    "city": "Paris",
    "country": "France",
    "address": "8 Rue de Poitou, 75003 Paris",
    "description": "The Cambridge Public House is a \"Cocktail Pub\" in Paris' Marais district, blending the relaxed vibe of a British pub with expert...",
    "instagram": "@thecambridge_paris",
    "instagram_url": "https://www.instagram.com/thecambridge_paris",
    "website": "https://www.thecambridge.paris/",
    "phone": "+33 6 44 63 80 78",
    "gradient": "linear-gradient(135deg, hsl(93, 30%, 15%), hsl(133, 25%, 10%))",
    "ranking_badge": "#20 World's Best",
    "rankings": "World's 50 Best Bars 2025 #20; Top 500 Bars 2025 #14"
  },
  {
    "name": "Satan's Whiskers",
    "city": "London",
    "country": "United Kingdom",
    "address": "343 Cambridge Heath Road, London, E2 9RA",
    "description": "Bethnal Green’s original neighbourhood cocktail bar known for exceptional classic cocktails served to a hip-hop soundtrack with a daily...",
    "instagram": "@satans_whiskers",
    "instagram_url": "https://www.instagram.com/satans_whiskers",
    "website": "https://www.satanswhiskers.com",
    "phone": "+44 20 7739 8362",
    "gradient": "linear-gradient(135deg, hsl(250, 30%, 15%), hsl(290, 25%, 10%))",
    "ranking_badge": "#21 World's Best",
    "rankings": "World's 50 Best Bars 2025 #21; Top 500 Bars 2025 #22"
  },
  {
    "name": "Tlecan",
    "city": "Mexico City",
    "country": "Mexico",
    "address": "Av. Álvaro Obregón 228-Local 2, Roma Nte., Cuauhtémoc, 06700 Ciudad de México, CDMX, Mexico",
    "description": "Tlecān is a mezcalería inspired by pre-Hispanic culture, specializing in artisanal agave distillates from small Mexican producers,...",
    "instagram": "@tlecan",
    "instagram_url": "https://www.instagram.com/tlecan",
    "website": "https://tlecan.com",
    "phone": "+52 55 1334 4745",
    "gradient": "linear-gradient(135deg, hsl(303, 30%, 15%), hsl(343, 25%, 10%))",
    "ranking_badge": "#23 World's Best",
    "rankings": "World's 50 Best Bars 2025 #23; North America's 50 Best Bars 2025 #3; Top 500 Bars 2025 #33"
  },
  {
    "name": "Tan Tan",
    "city": "São Paulo",
    "country": "Brazil",
    "address": "R. Fradique Coutinho, 153 - Pinheiros, São Paulo - SP, 05416-010",
    "description": "Tan Tan is an intimate yet buzzing cocktail bar and restaurant in São Paulo's Pinheiros district, blending Brazilian-Asian flavors with...",
    "instagram": "@tantannb",
    "instagram_url": "https://www.instagram.com/tantannb",
    "website": "http://www.tantan.com.br",
    "phone": "+55 11 2373-3587",
    "gradient": "linear-gradient(135deg, hsl(286, 30%, 15%), hsl(326, 25%, 10%))",
    "ranking_badge": "#24 World's Best",
    "rankings": "World's 50 Best Bars 2025 #24; Top 500 Bars 2025 #19"
  },
  {
    "name": "Mirror Bar",
    "city": "Bratislava",
    "country": "Slovakia",
    "address": "Radisson Blu Carlton Hotel, Hviezdoslavovo námestie 3, 811 02 Bratislava, Slovakia",
    "description": "Located in Bratislava's historic Radisson Blu Carlton Hotel, Mirror Bar is a prestigious lounge known for its art-inspired cocktails,...",
    "instagram": "@mirrorbarcarlton",
    "instagram_url": "https://www.instagram.com/mirrorbarcarlton",
    "website": "https://www.mirrorbarcarlton.com/",
    "phone": "+421 2 59 390 402",
    "gradient": "linear-gradient(135deg, hsl(163, 30%, 15%), hsl(203, 25%, 10%))",
    "ranking_badge": "#25 World's Best",
    "rankings": "World's 50 Best Bars 2025 #25; Top 500 Bars 2025 #46"
  },
  {
    "name": "CoChinChina",
    "city": "Buenos Aires",
    "country": "Argentina",
    "address": "Armenia 1540, C1414 Buenos Aires",
    "description": "Theatrical Franco-Vietnamese cocktail bar in Palermo known for innovative drinks by Inés de los Santos, immersive Asian-inspired decor,...",
    "instagram": "@cochinchina.bar",
    "instagram_url": "https://www.instagram.com/cochinchina.bar",
    "website": "https://cochinchina.bar",
    "phone": "+54 9 11 2247-6452",
    "gradient": "linear-gradient(135deg, hsl(72, 30%, 15%), hsl(112, 25%, 10%))",
    "ranking_badge": "#26 World's Best",
    "rankings": "World's 50 Best Bars 2025 #26; Top 500 Bars 2025 #23"
  },
  {
    "name": "Baba au Rum",
    "city": "Athens",
    "country": "Greece",
    "address": "Klitiou 6, Athens 105 60",
    "description": "Award-winning rum and cocktail bar known for its extensive collection of over 400 rums, innovative tiki-inspired cocktails, and warm,...",
    "instagram": "@baba_au_rum",
    "instagram_url": "https://www.instagram.com/baba_au_rum",
    "website": "https://www.babaaurum.com",
    "phone": "+30 21 1710 9140",
    "gradient": "linear-gradient(135deg, hsl(47, 30%, 15%), hsl(87, 25%, 10%))",
    "ranking_badge": "#27 World's Best",
    "rankings": "World's 50 Best Bars 2025 #27; Top 500 Bars 2025 #20"
  },
  {
    "name": "Nouvelle Vague",
    "city": "Tirana",
    "country": "Albania",
    "address": "Rruga Pjetër Bogdani, Tirana, Albania",
    "description": "Pioneering cocktail bar since 2012, blending local Albanian flavors with modern mixology in an intimate, stylish space inspired by...",
    "instagram": "@nouvellevague_tirana",
    "instagram_url": "https://www.instagram.com/nouvellevague_tirana",
    "website": "https://nouvellevaguetirana.com",
    "phone": "+355 69 933 3622",
    "gradient": "linear-gradient(135deg, hsl(51, 30%, 15%), hsl(91, 25%, 10%))",
    "ranking_badge": "#28 World's Best",
    "rankings": "World's 50 Best Bars 2025 #28; Top 500 Bars 2025 #39"
  },
  {
    "name": "Hope & Sesame",
    "city": "Guangzhou",
    "country": "China",
    "address": "No. 58 Miaoqian West Street (Miaoqian Xijie 58), Dongshankou, Yuexiu District",
    "description": "Hope & Sesame is a pioneering speakeasy cocktail bar hidden behind a traditional Cantonese cha chaan teng in Guangzhou's historic...",
    "instagram": "@hopeandsesame",
    "instagram_url": "https://www.instagram.com/hopeandsesame",
    "website": "https://hopeandsesame.cn/home/hope-sesame-guangzhou/",
    "phone": "+86 189 9841 8723",
    "gradient": "linear-gradient(135deg, hsl(0, 30%, 15%), hsl(40, 25%, 10%))",
    "ranking_badge": "#29 World's Best",
    "rankings": "World's 50 Best Bars 2025 #29; Asia's 50 Best Bars 2025 #7; Top 500 Bars 2025 #26"
  },
  {
    "name": "Danico",
    "city": "Paris",
    "country": "France",
    "address": "6 Rue Vivienne, 75002 Paris",
    "description": "Danico is a renowned speakeasy-style cocktail bar in Paris's historic Galerie Vivienne, known for its inventive, globe-trotting menus...",
    "instagram": "@danicoparis",
    "instagram_url": "https://www.instagram.com/danicoparis",
    "website": "http://www.daroco.com/en/danico/",
    "phone": "+33 1 42 21 93 71",
    "gradient": "linear-gradient(135deg, hsl(55, 30%, 15%), hsl(95, 25%, 10%))",
    "ranking_badge": "#30 World's Best",
    "rankings": "World's 50 Best Bars 2025 #30; Top 500 Bars 2025 #17"
  },
  {
    "name": "Scarfes Bar",
    "city": "London",
    "country": "United Kingdom",
    "address": "252 High Holborn, London, WC1V 7EN",
    "description": "An artfully social cocktail bar in Holborn with live jazz daily, renowned for creative cocktails and a sophisticated vibe inspired by...",
    "instagram": "@scarfesbar",
    "instagram_url": "https://www.instagram.com/scarfesbar",
    "website": "https://scarfesbar.com/",
    "phone": "+44 20 3747 8670",
    "gradient": "linear-gradient(135deg, hsl(232, 30%, 15%), hsl(272, 25%, 10%))",
    "ranking_badge": "#31 World's Best",
    "rankings": "World's 50 Best Bars 2025 #31"
  },
  {
    "name": "Svanen",
    "city": "Oslo",
    "country": "Norway",
    "address": "Karl Johans gate 13, 0154 Oslo",
    "description": "Cocktail bar in a preserved 1896 neoclassical pharmacy with marble columns and swan motifs, known for modern twists on classics and...",
    "instagram": "@svanen.oslo",
    "instagram_url": "https://www.instagram.com/svanen.oslo",
    "website": "https://www.svanenoslo.no",
    "phone": "+47 984 38 613",
    "gradient": "linear-gradient(135deg, hsl(240, 30%, 15%), hsl(280, 25%, 10%))",
    "ranking_badge": "#32 World's Best",
    "rankings": "World's 50 Best Bars 2025 #32; Top 500 Bars 2025 #88"
  },
  {
    "name": "Sastrería Martinez",
    "city": "Lima",
    "country": "Peru",
    "address": "Av. Mariscal La Mar 1263, Miraflores, Lima 15074",
    "description": "Speakeasy cocktail bar hidden behind a tailor shop facade in Miraflores, inspired by Prohibition-era aesthetics, known for precisely...",
    "instagram": "@sastreriamartinezlima",
    "instagram_url": "https://www.instagram.com/sastreriamartinezlima",
    "website": "https://www.sastreriamartinez.com",
    "phone": "+51 923 098 735",
    "gradient": "linear-gradient(135deg, hsl(89, 30%, 15%), hsl(129, 25%, 10%))",
    "ranking_badge": "#33 World's Best",
    "rankings": "World's 50 Best Bars 2025 #33"
  },
  {
    "name": "Panda & Sons",
    "city": "Edinburgh",
    "country": "United Kingdom",
    "address": "79 Queen Street, Edinburgh EH2 4NF",
    "description": "Panda & Sons is a renowned speakeasy-style cocktail bar hidden behind a vintage barbershop entrance on Queen Street, celebrated for its...",
    "instagram": "@pandaandsons",
    "instagram_url": "https://www.instagram.com/pandaandsons",
    "website": "https://pandaandsons.com",
    "phone": "+44 131 220 0443",
    "gradient": "linear-gradient(135deg, hsl(54, 30%, 15%), hsl(94, 25%, 10%))",
    "ranking_badge": "#34 World's Best",
    "rankings": "World's 50 Best Bars 2025 #34; Top 500 Bars 2025 #1; Spirited Awards 2025: World's Best Cocktail Menu (Spirited Awards)"
  },
  {
    "name": "Röda Huset",
    "city": "Stockholm",
    "country": "Sweden",
    "address": "Malmskillnadsgatan 9, 111 57 Stockholm, Sweden",
    "description": "Röda Huset is Stockholm's hyper-local cocktail bar known for Nordic ingredients, seasonal foraging, and minimalist precision in its...",
    "instagram": "@rodahusetsthlm",
    "instagram_url": "https://www.instagram.com/rodahusetsthlm",
    "website": "https://rodahuset.nu/",
    "phone": "+46 8 480 043 97",
    "gradient": "linear-gradient(135deg, hsl(145, 30%, 15%), hsl(185, 25%, 10%))",
    "ranking_badge": "#35 World's Best",
    "rankings": "World's 50 Best Bars 2025 #35"
  },
  {
    "name": "Mimi Kakushi",
    "city": "Dubai",
    "country": "United Arab Emirates",
    "address": "Restaurant Village, Four Seasons Resort, Jumeirah Beach Road, Dubai, UAE",
    "description": "Mimi Kakushi is a stylish cocktail bar and Japanese restaurant inspired by 1920s Osaka, featuring jazz-age vibes, ice-carved martinis,...",
    "instagram": "@mimikakushi",
    "instagram_url": "https://www.instagram.com/mimikakushi",
    "website": "https://mimikakushi.ae",
    "phone": "+971 4 379 4811",
    "gradient": "linear-gradient(135deg, hsl(89, 30%, 15%), hsl(129, 25%, 10%))",
    "ranking_badge": "#36 World's Best",
    "rankings": "World's 50 Best Bars 2025 #36; Top 500 Bars 2025 #64; Barmagazine Dubai Top 10 2025 #1"
  },
  {
    "name": "Salmon Guru",
    "city": "Madrid",
    "country": "Spain",
    "address": "Calle de Echegaray, 21, 28014 Madrid, Spain",
    "description": "Eclectic cocktail bar and restaurant known for inventive, theatrical cocktails served in quirky vessels, bold visuals, high-energy...",
    "instagram": "@salmonguru",
    "instagram_url": "https://www.instagram.com/salmonguru",
    "website": "https://salmonguru.es/en/",
    "phone": "+34 910 00 61 85",
    "gradient": "linear-gradient(135deg, hsl(22, 30%, 15%), hsl(62, 25%, 10%))",
    "ranking_badge": "#37 World's Best",
    "rankings": "World's 50 Best Bars 2025 #37; Top 500 Bars 2025 #11"
  },
  {
    "name": "Coa",
    "city": "Hong Kong",
    "country": "China",
    "address": "Shop A, LG/F, Wah Shin House, 6-10 Shin Hing Street, Central, Hong Kong",
    "description": "Coa is a Mexican-inspired cocktail bar renowned as an agave spirit authority, specializing in 100% agave tequila, traditional mezcal,...",
    "instagram": "@coahongkong",
    "instagram_url": "https://www.instagram.com/coahongkong",
    "website": "https://coa.com.hk",
    "phone": "+852 2813 5787",
    "gradient": "linear-gradient(135deg, hsl(262, 30%, 15%), hsl(302, 25%, 10%))",
    "ranking_badge": "#38 World's Best",
    "rankings": "World's 50 Best Bars 2025 #38; Asia's 50 Best Bars 2025 #17; Top 500 Bars 2025 #28"
  },
  {
    "name": "Sip & Guzzle",
    "city": "New York",
    "country": "USA",
    "address": "29 Cornelia St, New York, NY 10014",
    "description": "Bi-level cocktail bar featuring Sip downstairs—an intimate speakeasy with bespoke cocktails by Shingo Gokan and Ben Yabrow, and...",
    "instagram": "@sipandguzzlenyc",
    "instagram_url": "https://www.instagram.com/sipandguzzlenyc",
    "website": "https://www.sipandguzzlenyc.com",
    "phone": "",
    "gradient": "linear-gradient(135deg, hsl(115, 30%, 15%), hsl(155, 25%, 10%))",
    "ranking_badge": "#39 World's Best",
    "rankings": "World's 50 Best Bars 2025 #39; North America's 50 Best Bars 2025 #5; Top 500 Bars 2025 #51; Spirited Awards 2025: Best New U.S. Cocktail Bar"
  },
  {
    "name": "Drink Kong",
    "city": "Rome",
    "country": "Italy",
    "address": "Piazza di San Martino ai Monti 8, 00184 Rome, Italy",
    "description": "Retro-futuristic cocktail bar with neon lighting and sleek dark aesthetics, known for innovative neoclassic cocktails like the Gaijin...",
    "instagram": "@drinkkongbar",
    "instagram_url": "https://www.instagram.com/drinkkongbar",
    "website": "https://www.drinkkong.com",
    "phone": "+39 06 2348 8666",
    "gradient": "linear-gradient(135deg, hsl(341, 30%, 15%), hsl(21, 25%, 10%))",
    "ranking_badge": "#40 World's Best",
    "rankings": "World's 50 Best Bars 2025 #40; Top 500 Bars 2025 #27"
  },
  {
    "name": "Double Chicken Please",
    "city": "New York",
    "country": "USA",
    "address": "115 Allen St, New York, NY 10002",
    "description": "Double Chicken Please is a design-driven cocktail bar on NYC's Lower East Side known for innovative \"design hacking\" cocktails that...",
    "instagram": "@doublechickenpleasenyc",
    "instagram_url": "https://www.instagram.com/doublechickenpleasenyc",
    "website": "https://doublechickenplease.com",
    "phone": "(646) 678-5452",
    "gradient": "linear-gradient(135deg, hsl(91, 30%, 15%), hsl(131, 25%, 10%))",
    "ranking_badge": "#41 World's Best",
    "rankings": "World's 50 Best Bars 2025 #41; North America's 50 Best Bars 2025 #19; Top 500 Bars 2025 #49"
  },
  {
    "name": "Maybe Sammy",
    "city": "Sydney",
    "country": "Australia",
    "address": "115 Harrington Street, The Rocks, Sydney, NSW 2000",
    "description": "Maybe Sammy is a glamorous cocktail bar inspired by 1950s Hollywood and Vegas, known for innovative movie-themed cocktails, mini...",
    "instagram": "@maybe_sammy_sydney",
    "instagram_url": "https://www.instagram.com/maybe_sammy_sydney",
    "website": "https://www.maybesammy.com",
    "phone": "+61 2 9241 4970",
    "gradient": "linear-gradient(135deg, hsl(61, 30%, 15%), hsl(101, 25%, 10%))",
    "ranking_badge": "#42 World's Best",
    "rankings": "World's 50 Best Bars 2025 #42; Top 500 Bars 2025 #16"
  },
  {
    "name": "1930",
    "city": "Milan",
    "country": "Italy",
    "address": "Basement of Mag La Pusterla, Via Edmondo de Amicis 22, 20123 Milan",
    "description": "1930 is an exclusive speakeasy cocktail bar known for its Prohibition-era vibe, innovative gastronomic cocktails that blend food and...",
    "instagram": "@1930cocktailbar",
    "instagram_url": "https://www.instagram.com/1930cocktailbar",
    "website": "",
    "phone": "+39 342 545 4860 (Mag La Pusterla)",
    "gradient": "linear-gradient(135deg, hsl(157, 30%, 15%), hsl(197, 25%, 10%))",
    "ranking_badge": "#43 World's Best",
    "rankings": "World's 50 Best Bars 2025 #43; Top 500 Bars 2025 #158"
  },
  {
    "name": "Jewel of the South",
    "city": "New Orleans",
    "country": "USA",
    "address": "1026 Saint Louis St, New Orleans, LA 70112",
    "description": "Jewel of the South is a James Beard Award-winning cocktail bar and tavern in a historic 19th-century Creole cottage in the French...",
    "instagram": "@jewelnola",
    "instagram_url": "https://www.instagram.com/jewelnola",
    "website": "https://www.jewelnola.com",
    "phone": "504-265-8816",
    "gradient": "linear-gradient(135deg, hsl(350, 30%, 15%), hsl(30, 25%, 10%))",
    "ranking_badge": "#44 World's Best",
    "rankings": "World's 50 Best Bars 2025 #44; North America's 50 Best Bars 2025 #4; Top 500 Bars 2025 #36"
  },
  {
    "name": "Virtù",
    "city": "Tokyo",
    "country": "Japan",
    "address": "1 Chome-2-1 Ōtemachi, Chiyoda City, Tokyo 100-0004, Four Seasons Hotel Tokyo at Otemachi",
    "description": "High above the city on the 39th floor of the Four Seasons Hotel Tokyo at Otemachi, Virtù offers Franco-Japanese cocktails with skyline...",
    "instagram": "@virtutokyo",
    "instagram_url": "https://www.instagram.com/virtutokyo",
    "website": "https://www.fourseasons.com/otemachi/dining/restaurants/virtu/",
    "phone": "+81 3-6810-0655",
    "gradient": "linear-gradient(135deg, hsl(262, 30%, 15%), hsl(302, 25%, 10%))",
    "ranking_badge": "#45 World's Best",
    "rankings": "World's 50 Best Bars 2025 #45; Asia's 50 Best Bars 2025 #18"
  },
  {
    "name": "Dr. Stravinsky",
    "city": "Barcelona",
    "country": "Spain",
    "address": "Carrer dels Mirallers, 5, 08003 Barcelona",
    "description": "Dr. Stravinsky is a countercultural cocktail bar in Barcelona's El Born neighborhood, designed like a 19th-century laboratory where...",
    "instagram": "@dr",
    "instagram_url": "https://www.instagram.com/dr.stravinskybcn",
    "website": "https://drstravinsky.cat/en/",
    "phone": "+34 937 97 89 45",
    "gradient": "linear-gradient(135deg, hsl(109, 30%, 15%), hsl(149, 25%, 10%))",
    "ranking_badge": "",
    "rankings": "World's 50 Best Bars 2025 #83; Top 500 Bars 2025 #29"
  },
  {
    "name": "Gucci Giardino",
    "city": "Florence",
    "country": "Italy",
    "address": "Piazza della Signoria, 37r, 50122 Firenze",
    "description": "Gucci Giardino is Gucci's all-day café and cocktail bar in Florence's Piazza della Signoria, inspired by a historic florist with...",
    "instagram": "@explore",
    "instagram_url": "https://www.instagram.com/explore/locations/100727739213800/gucci-giardino",
    "website": "https://www.gucciosteria.com/en/florence/giardino",
    "phone": "+39 055 75927012",
    "gradient": "linear-gradient(135deg, hsl(260, 30%, 15%), hsl(300, 25%, 10%))",
    "ranking_badge": "",
    "rankings": "World's 50 Best Bars 2025 #99; Top 500 Bars 2025 #31"
  },
  {
    "name": "Tayēr + Elementary",
    "city": "London",
    "country": "United Kingdom",
    "address": "152 Old Street, London, EC1V 9BW",
    "description": "Tayēr + Elementary is a produce-driven cocktail bar in two parts: Elementary, a neighborhood spot with ready-to-drink classics on tap,...",
    "instagram": "@tayer_elementary",
    "instagram_url": "https://www.instagram.com/tayer_elementary",
    "website": "https://tayer-elementary.com",
    "phone": "020 3011 1153",
    "gradient": "linear-gradient(135deg, hsl(324, 30%, 15%), hsl(4, 25%, 10%))",
    "ranking_badge": "",
    "rankings": ""
  },
  {
    "name": "The Clumsies",
    "city": "Athens",
    "country": "Greece",
    "address": "30 Praxitelous, Athens 105 61, Greece",
    "description": "An all-day cocktail bar in central Athens known for unique, creative cocktails by award-winning Greek bartenders, a warm homely vibe...",
    "instagram": "@the_clumsies",
    "instagram_url": "https://www.instagram.com/the_clumsies",
    "website": "https://www.theclumsies.gr",
    "phone": "+30 210 323 2682",
    "gradient": "linear-gradient(135deg, hsl(5, 30%, 15%), hsl(45, 25%, 10%))",
    "ranking_badge": "",
    "rankings": "Top 500 Bars 2025 #32"
  },
  {
    "name": "Locale Firenze",
    "city": "Firenze",
    "country": "Italy",
    "address": "Via delle Seggiole, 12r, 50122 Firenze FI, Italy",
    "description": "Housed in the historic 13th-century Palazzo Concini, Locale Firenze is a renowned cocktail bar blending cutting-edge mixology with...",
    "instagram": "@localefirenze",
    "instagram_url": "https://www.instagram.com/localefirenze",
    "website": "https://www.localefirenze.it/",
    "phone": "+39 055 906 7188",
    "gradient": "linear-gradient(135deg, hsl(145, 30%, 15%), hsl(185, 25%, 10%))",
    "ranking_badge": "",
    "rankings": ""
  },
  {
    "name": "Devil's Cut",
    "city": "Madrid",
    "country": "Spain",
    "address": "Calle de León 3, 28014 Madrid, Spain",
    "description": "Cocktail bar in Madrid's Las Letras neighborhood blending Japanese mixology influences with Jerez sherry wines, featuring signature...",
    "instagram": "@devilscut.madrid",
    "instagram_url": "https://www.instagram.com/devilscut.madrid",
    "website": "https://devilscutmadrid.com/",
    "phone": "Not publicly listed",
    "gradient": "linear-gradient(135deg, hsl(242, 30%, 15%), hsl(282, 25%, 10%))",
    "ranking_badge": "Spirited Award Winner",
    "rankings": "Top 500 Bars 2025 #34; Spirited Awards 2025: Best New International Cocktail Bar"
  },
  {
    "name": "Angelita Madrid",
    "city": "Madrid",
    "country": "Spain",
    "address": "Calle de la Reina, 4, 28004 Madrid, Spain",
    "description": "Angelita is a renowned wine bar and gastro cocktail bar in Chueca, featuring an upstairs area with seasonal farm-to-table Mediterranean...",
    "instagram": "@madridangelita",
    "instagram_url": "https://www.instagram.com/madridangelita",
    "website": "https://madrid-angelita.es",
    "phone": "+34 915 21 66 78",
    "gradient": "linear-gradient(135deg, hsl(89, 30%, 15%), hsl(129, 25%, 10%))",
    "ranking_badge": "",
    "rankings": ""
  }
];