/**
 * Hand-written intros for the country-by-type and US-state-by-type pages
 * (Roman, 2026-09-16). Keyed "country:<country-slug>:<type-slug>" and
 * "us:<state-slug>:<type-slug>".
 *
 * PRIMARY-SOURCE RULE: every named bar, rank and award below comes from
 * our own bars.accolades records (World's 50 Best 2025, North America's
 * 50 Best 2026, Spirited Awards 2023 to 2026, The Pinnacle Guide 2026),
 * checked against the database on 2026-09-16. No em dashes; US English.
 * Counts are never written here: the page prints the live count itself.
 */
export const REGION_INTROS: Record<string, string> = {
  'country:united-states:hotel-bars':
    "American hotel bars carry a century of the country's drinking history, from the Round Robin at the Willard in Washington, where the bar itself credits Henry Clay with introducing the Mint Julep to the capital, to the Tonga Room's floating band at the Fairmont San Francisco. The modern bench is just as deep. Hey Love in Portland won Best U.S. Hotel Bar at the 2023 Spirited Awards, Allegory in Washington DC took World's Best Cocktail Menu at the 2026 awards, and Silver Lyan across town holds a place on North America's 50 Best Bars. Las Vegas and New Orleans lead the country by count, Washington DC, New York and San Francisco follow, and the list runs from the Polo Lounge in Beverly Hills to Z Bar above Michigan Avenue in Chicago. Every listing is verified by BarMagazine, with the hotel named, the address, the hours the venue publishes and the drinks worth ordering.",
  'country:united-states:speakeasies':
    "The speakeasy is an American invention, and the country still does it best. New York has the deepest set: Sip & Guzzle and Attaboy both hold places on the World's 50 Best Bars, Employees Only has been a Manhattan institution since the West Village room opened, and Raines Law Room keeps the unmarked-door tradition alive on 17th Street. Allegory in Washington DC, hidden behind the lobby of the Eaton hotel, won World's Best Cocktail Menu at the 2026 Spirited Awards, and Meadowlark in Chicago sits on North America's 50 Best Bars. San Diego, Boston and Seattle each have enough hidden rooms to earn their own city guides. The pages below list every speakeasy we have verified across the United States, with the entrance explained where the venue explains it, the address, the hours published and the signature drinks.",
  'country:united-states:rooftop-bars':
    "Rooftop bars in the United States range from the Manhattan skyline rooms to a Washington DC scene that has quietly become one of the strongest in the country. Overstory, sixty-four floors up in the Financial District, holds a place on the World's 50 Best Bars, and Apothéke NoMad brings the group's apothecary style to a terrace above the Ace Hotel. In Washington, Amazonia was a Top 10 nominee for Best U.S. Restaurant Bar at the 2026 Spirited Awards, and Copycat Co. and Jack Rose Dining Saloon both carry our Top 10 pick. Bar Lis in Los Angeles, a Miami room and a Boston terrace round out the set. Rooftops keep shorter seasons and weather-dependent hours than street-level bars, so the hours below are the ones each venue publishes and are worth a check before a visit. Every listing is verified by BarMagazine.",
  'country:united-states:cocktail-bars':
    "The United States has the largest cocktail bar bench in the BarMagazine directory, and the top of it is world class. Superbueno in New York ranks twelfth on the World's 50 Best Bars, with Sip & Guzzle, Double Chicken Please and Overstory also on the global list, and Jewel of the South carries New Orleans into the top fifty. North America's 50 Best Bars 2026 puts Bar Snack and Schmuck, both New York rooms, in its top five, and True Laurel in San Francisco in its top fifteen. New York leads the count, followed by Chicago, Los Angeles, New Orleans, Miami and Seattle, and dozens of smaller cities from Portland, Maine to Shawnee, Kansas hold James Beard Outstanding Bar honorees. This page lists every cocktail bar we have verified in the country; the city guides linked below rank the best of each city, and every profile carries the address, published hours and the drinks to order.",
  'us:california:hotel-bars':
    "California's hotel bars split between San Francisco's grand rooms and the Los Angeles scene around Sunset Boulevard. San Francisco holds the Tonga Room at the Fairmont, with its lagoon and floating band, Starlite, a Regional Honoree for Best U.S. Hotel Bar at the 2026 Spirited Awards, and Bar Maritime and Cavaña, both 2026 Regional Honorees for Best New U.S. Cocktail Bar. Down the coast, The Manor Bar in Montecito was a Top 10 nominee for Best U.S. Hotel Bar in 2026, and the Polo Lounge at The Beverly Hills Hotel keeps the room the hotel calls Hollywood's commissary, complete with its candy-striped ceiling and Sunday jazz brunch. Bar Lis in Los Angeles and a San Diego room complete the set. Every listing is verified by BarMagazine, with the hotel named, the address, the hours the venue publishes and the signature drinks.",
  'us:california:cocktail-bars':
    "California's cocktail bars are led by San Francisco and Los Angeles, with San Diego close behind. True Laurel in the Mission ranks fourteenth on North America's 50 Best Bars 2026, Pacific Cocktail Haven and Trick Dog, the 2025 Spirited Award winner for Best U.S. Cocktail Bar, are San Francisco fixtures, and the Buena Vista Cafe won the Timeless U.S. Award in 2024 for the Irish Coffee it has poured since 1952. In Los Angeles, Mírate in Los Feliz and Daisy Margarita Bar both hold places on North America's 50 Best Bars 2026, and the agave-led rooms of the east side share the list with the classic bars of Hollywood and downtown. San Diego adds a strong set around North Park and Little Italy, and Sacramento, Oakland and Long Beach each have entries. Every listing is verified by BarMagazine, with the address, published hours and the drinks worth ordering, and the city guides linked below rank each city's best.",
  'us:new-york:hotel-bars':
    "New York's hotel bars are where the city's cocktail history was written, and the current set holds up to it. The Portrait Bar at the Fifth Avenue Hotel ranks on North America's 50 Best Bars 2026, the Lobby Bar at The Hotel Chelsea and Nubeluz atop the Ritz-Carlton NoMad were both Regional Honorees for Best U.S. Hotel Bar at the 2026 Spirited Awards, and Raines Law Room at the William was a Top 10 nominee in the same category. Bemelmans Bar at The Carlyle, with its Ludwig Bemelmans murals, is the room every visitor is sent to first. Every listing is verified by BarMagazine, with the hotel named, the address, the hours the venue publishes and the signature drinks worth ordering.",
  'us:new-york:cocktail-bars':
    "New York remains the deepest cocktail city in the United States, and the rankings say so. Superbueno ranks twelfth on the World's 50 Best Bars 2025, with Sip & Guzzle, Double Chicken Please and Overstory also on the global list, and North America's 50 Best Bars 2026 places Bar Snack third and Schmuck fourth. Beyond the ranked rooms the bench is long: Attaboy and Employees Only in Manhattan, Amor y Amargo and its bitters-led menu in the East Village, and the Brooklyn rooms that have reshaped how the city drinks. The list below covers every New York cocktail bar we have verified, from Midtown hotel classics to Bed-Stuy and Williamsburg, each with the address, published hours and the drinks to order. The city guide linked below ranks the best of them.",
  'us:texas:hotel-bars':
    "Texas hotel bars are concentrated in Dallas, Houston and Austin, and the recent Spirited Awards have noticed. Midnight Rambler, below the Joule in downtown Dallas, was a Top 10 nominee for Best U.S. Hotel Bar in 2026, and Catbird, on the rooftop of the Thompson Dallas, was a Regional Honoree in the same category. Bandista in Houston holds a place on North America's 50 Best Bars 2026, and Equipment Room in Austin, the listening bar beneath the Hotel Magdalena, carries our Top 10 pick. Every listing is verified by BarMagazine, with the hotel named, the address, the hours the venue publishes and the signature drinks worth ordering.",
  'us:texas:cocktail-bars':
    "Austin leads Texas by count, with Houston close behind and Dallas holding its own. Bandista in Houston ranks on North America's 50 Best Bars 2026, and the 2026 Spirited Awards named a string of Texas Regional Honorees: Bar Fino in Austin for Best New U.S. Cocktail Bar, Holiday in Austin for Best U.S. Restaurant Bar, Johnny's Gold Brick in Houston for Best U.S. Bar Team and Catbird in Dallas for Best U.S. Hotel Bar, with Midnight Rambler in Dallas a Top 10 nominee for Best U.S. Hotel Bar. Nickel City and The Roosevelt Room anchor the Austin scene, and Brownsville adds a James Beard Outstanding Bar honoree. The list below covers every Texas cocktail bar we have verified, each with the address, published hours and the drinks worth ordering; the city guides linked below rank each city's best.",
  'us:florida:hotel-bars':
    "Florida's hotel bars are a Miami story with a Palm Beach coda. The Broken Shaker at the Freehand, which carries our Top 10 pick, is the room that put Miami's cocktail scene on the map, and Swizzle Rum Bar & Drinkery brings the Caribbean rum tradition to Brickell. Viceversa, the winner of Best U.S. Hotel Bar at the 2026 Spirited Awards, sits in the same city. In Palm Beach, HMF at The Breakers occupies the former Florentine Room off the resort's grand lobby, with a wine list of more than 2,200 selections. Every listing is verified by BarMagazine, with the hotel named, the address, the hours the venue publishes and the signature drinks worth ordering.",
  'us:florida:cocktail-bars':
    "Miami carries Florida's cocktail scene, and the awards have followed. Viceversa won Best U.S. Hotel Bar at the 2026 Spirited Awards, Café La Trova holds a place on the World's 50 Best Bars 2025 for its cantinero tradition, and Bar Kaiju ranks on North America's 50 Best Bars 2026. The Champagne Bar at the Four Seasons Surf Club carries 3 Pins from The Pinnacle Guide 2026, and LPM Miami and Macchialina in Miami Beach were both Regional Honorees for Best U.S. Restaurant Bar in 2026. The list below covers every Florida cocktail bar we have verified, from Wynwood and Little Havana to the beach, each with the address, published hours and the drinks worth ordering; the Miami guide linked below ranks the city's best.",
};

export function regionIntro(key: string): string | null {
  return REGION_INTROS[key] ?? null;
}
