#!/bin/bash
# Arm ONE one-shot send window as a launchd calendar agent.
#
#   outreach/arm-window.sh <batch-label> <window> <MM> <DD> <HH> <MM> <slugs-file>
#   outreach/arm-window.sh batch15-asia w1 09 21 21 00 outreach/batch15-w1.slugs
#
# Writes outreach/<batch>-runner-<window>.sh and the matching LaunchAgent, then
# loads it and prints the schedule back.
#
# The runner DELETES ITS PLIST BEFORE UNLOADING: "launchctl unload" terminates
# the running job, so anything after it on the line never executes. Batch 14 w1
# proved this on 2026-09-16, leaving a spent one-shot armed with a past date,
# which fires again at the next login and re-sends. Order matters here.
set -euo pipefail

BATCH="$1"; WIN="$2"; MONTH="$3"; DAY="$4"; HOUR="$5"; MINUTE="$6"; SLUGS="$7"
REPO="/Users/romanzelenka/barmagazine-next"
LABEL="com.barmagazine.${BATCH}-${WIN}"
RUNNER="$REPO/outreach/${BATCH}-runner-${WIN}.sh"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
LOG="$REPO/outreach/${BATCH}-send.log"

[ -s "$REPO/$SLUGS" ] || { echo "FATAL: $SLUGS is missing or empty, nothing armed"; exit 1; }

cat > "$RUNNER" <<RUNNER_EOF
#!/bin/bash
# One-shot runner for ${BATCH} window ${WIN}, armed $(date +%Y-%m-%d) for
# 2026-${MONTH}-${DAY} ${HOUR}:${MINUTE} PT. Generated by outreach/arm-window.sh.
set -u
REPO="${REPO}"
LOG="${LOG}"
cd "\$REPO" || exit 1
echo "=== ${BATCH} ${WIN} live send \$(date) ===" >> "\$LOG"
/usr/local/bin/node scripts/send-upsell.mjs --send --batch ${BATCH} \$(cat ${SLUGS}) >> "\$LOG" 2>&1
echo "=== ${BATCH} ${WIN} done \$(date) ===" >> "\$LOG"
# Delete first, then unload: the unload kills this job (batch 14 w1, 2026-09-16).
rm -f "${PLIST}"
launchctl bootout gui/\$(id -u)/${LABEL} >> "\$LOG" 2>&1 || true
RUNNER_EOF
chmod +x "$RUNNER"
bash -n "$RUNNER"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array><string>/bin/bash</string><string>-lc</string><string>${RUNNER}</string></array>
  <key>StandardOutPath</key><string>${REPO}/outreach/${LABEL}.launchd.log</string>
  <key>StandardErrorPath</key><string>${REPO}/outreach/${LABEL}.launchd.log</string>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Month</key><integer>${MONTH#0}</integer>
    <key>Day</key><integer>${DAY#0}</integer>
    <key>Hour</key><integer>${HOUR#0}</integer>
    <key>Minute</key><integer>${MINUTE#0}</integer>
  </dict>
</dict>
</plist>
PLIST_EOF
plutil -lint "$PLIST" > /dev/null

launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
echo "armed ${LABEL}: $(tr ' ' '\n' < "$REPO/$SLUGS" | grep -c . ) recipients"
/usr/libexec/PlistBuddy -c "Print :StartCalendarInterval" "$PLIST"
