#!/bin/bash
# Arm ONE one-shot send window as a launchd calendar agent.
#
#   outreach/arm-window.sh <batch-label> <window> <MM> <DD> <HH> <MM> <slugs-file> [extra send flags]
#   outreach/arm-window.sh batch15-asia w1 09 21 21 00 outreach/batch15-w1.slugs
#   outreach/arm-window.sh batch20-americas-us w1 09 29 09 00 outreach/batch20-americas-b.slugs --variant us
#
# Anything after the slugs file is passed to send-upsell.mjs as is (task 119:
# the A/B arms need --variant old / --variant us).
#
# Writes outreach/<batch>-runner-<window>.sh and the matching LaunchAgent, then
# loads it and prints the schedule back.
#
# The runner DELETES ITS PLIST BEFORE UNLOADING: "launchctl unload" terminates
# the running job, so anything after it on the line never executes. Batch 14 w1
# proved this on 2026-09-16, leaving a spent one-shot armed with a past date,
# which fires again at the next login and re-sends. Order matters here.
set -euo pipefail

BATCH="$1"; WIN="$2"; MONTH="$3"; DAY="$4"; HOUR="$5"; MINUTE="$6"; SLUGS="$7"; shift 7; EXTRA="$*"
REPO="/Users/romanzelenka/barmagazine-next"
LABEL="com.barmagazine.${BATCH}-${WIN}"
RUNNER="$REPO/outreach/${BATCH}-runner-${WIN}.sh"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
LOG="$REPO/outreach/${BATCH}-send.log"

[ -s "$REPO/$SLUGS" ] || { echo "FATAL: $SLUGS is missing or empty, nothing armed"; exit 1; }

cat > "$RUNNER" <<RUNNER_EOF
#!/bin/bash
# One-shot runner for ${BATCH} window ${WIN}, armed $(date +%Y-%m-%d) for
# 2026-${MONTH}-${DAY} ${HOUR}:${MINUTE} PT. Generated by outreach/arm-window.sh.
set -u
REPO="${REPO}"
LOG="${LOG}"
cd "\$REPO" || exit 1
echo "=== ${BATCH} ${WIN} live send \$(date) ===" >> "\$LOG"

# RETRY ON FAILURE: three attempts, then 10 minutes, then 30.
#
# WHY. Supabase went down on 2026-09-21 and took a dry run with it. A send
# that dies partway is not a batch that mostly worked: the window closes, the
# one-shot deletes itself, and the unsent remainder is simply lost until
# somebody notices.
#
# An outage is indistinguishable from a bad list at the point of failure.
# send-upsell.mjs runs a pre-flight that counts every slug it cannot resolve
# as "no email on file", and an unreachable Supabase fails to resolve ALL of
# them, so the script exits 2 saying the list is malformed when the list is
# fine. That is why ANY non-zero exit is retried and not just a crash.
#
# RETRIES ARE SAFE BECAUSE OF THE SENT LOG. send-upsell.mjs appends each bar
# to outreach/sent-log.txt the moment its mail is accepted, and skips on the
# next run anything already in it. So attempt 2 mails only what attempt 1 did
# not reach, and a fully successful batch re-run exits 0 having sent nothing.
# Without that guard this loop would be a way to mail people three times.
BACKOFF=(0 600 1800)
STATUS=1
for ATTEMPT in 0 1 2; do
  if [ "\${BACKOFF[\$ATTEMPT]}" -gt 0 ]; then
    echo "=== ${BATCH} ${WIN} attempt \$((ATTEMPT + 1)) waiting \${BACKOFF[\$ATTEMPT]}s \$(date) ===" >> "\$LOG"
    sleep "\${BACKOFF[\$ATTEMPT]}"
  fi
  echo "=== ${BATCH} ${WIN} attempt \$((ATTEMPT + 1)) start \$(date) ===" >> "\$LOG"
  /usr/local/bin/node scripts/send-upsell.mjs --send --batch ${BATCH} ${EXTRA} \$(cat ${SLUGS}) >> "\$LOG" 2>&1
  STATUS=\$?
  echo "=== ${BATCH} ${WIN} attempt \$((ATTEMPT + 1)) exit \$STATUS \$(date) ===" >> "\$LOG"
  [ "\$STATUS" -eq 0 ] && break
done

if [ "\$STATUS" -eq 0 ]; then
  echo "=== ${BATCH} ${WIN} done \$(date) ===" >> "\$LOG"
else
  echo "!!! ${BATCH} ${WIN} FAILED after 3 attempts, last exit \$STATUS \$(date)" >> "\$LOG"
  echo "!!! Anything already mailed is in outreach/sent-log.txt; re-running the" >> "\$LOG"
  echo "!!! same slug list sends only the remainder." >> "\$LOG"
fi

# Clean up even after a total failure. A spent one-shot left armed with a past
# date fires again at the next login and sends unattended, which is the batch
# 14 w1 incident (2026-09-16). Delete first, then unload: the unload kills this
# job, so anything after it never runs.
rm -f "${PLIST}"
launchctl bootout gui/\$(id -u)/${LABEL} >> "\$LOG" 2>&1 || true
RUNNER_EOF
chmod +x "$RUNNER"
bash -n "$RUNNER"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array><string>/bin/bash</string><string>-lc</string><string>${RUNNER}</string></array>
  <key>StandardOutPath</key><string>${REPO}/outreach/${LABEL}.launchd.log</string>
  <key>StandardErrorPath</key><string>${REPO}/outreach/${LABEL}.launchd.log</string>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Month</key><integer>${MONTH#0}</integer>
    <key>Day</key><integer>${DAY#0}</integer>
    <key>Hour</key><integer>${HOUR#0}</integer>
    <key>Minute</key><integer>${MINUTE#0}</integer>
  </dict>
</dict>
</plist>
PLIST_EOF
plutil -lint "$PLIST" > /dev/null

launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
echo "armed ${LABEL}: $(tr ' ' '\n' < "$REPO/$SLUGS" | grep -c . ) recipients"
/usr/libexec/PlistBuddy -c "Print :StartCalendarInterval" "$PLIST"
