#!/bin/bash
# One-shot runner for batch15-asia window w2, armed 2026-09-17 for
# 2026-09-20 23:00 PT. Generated by outreach/arm-window.sh.
set -u
REPO="/Users/romanzelenka/barmagazine-next"
LOG="/Users/romanzelenka/barmagazine-next/outreach/batch15-asia-send.log"
cd "$REPO" || exit 1
echo "=== batch15-asia w2 live send $(date) ===" >> "$LOG"
/usr/local/bin/node scripts/send-upsell.mjs --send --batch batch15-asia $(cat outreach/batch15-w2.slugs) >> "$LOG" 2>&1
echo "=== batch15-asia w2 done $(date) ===" >> "$LOG"
# Delete first, then unload: the unload kills this job (batch 14 w1, 2026-09-16).
rm -f "/Users/romanzelenka/Library/LaunchAgents/com.barmagazine.batch15-asia-w2.plist"
launchctl bootout gui/$(id -u)/com.barmagazine.batch15-asia-w2 >> "$LOG" 2>&1 || true
