#!/bin/bash
# One-shot runner for batch17-monday window w1, armed 2026-09-18 for
# 2026-09-21 00:30 PT. Generated by outreach/arm-window.sh.
set -u
REPO="/Users/romanzelenka/barmagazine-next"
LOG="/Users/romanzelenka/barmagazine-next/outreach/batch17-monday-send.log"
cd "$REPO" || exit 1
echo "=== batch17-monday w1 live send $(date) ===" >> "$LOG"
/usr/local/bin/node scripts/send-upsell.mjs --send --batch batch17-monday $(cat outreach/batch17-monday.slugs) >> "$LOG" 2>&1
echo "=== batch17-monday w1 done $(date) ===" >> "$LOG"
# Delete first, then unload: the unload kills this job (batch 14 w1, 2026-09-16).
rm -f "/Users/romanzelenka/Library/LaunchAgents/com.barmagazine.batch17-monday-w1.plist"
launchctl bootout gui/$(id -u)/com.barmagazine.batch17-monday-w1 >> "$LOG" 2>&1 || true
