#!/bin/bash
# One-shot runner for batch20-americas window w2, armed 2026-09-23 for
# 2026-09-29 09:05 PT. Generated by outreach/arm-window.sh.
set -u
REPO="/Users/romanzelenka/barmagazine-next"
LOG="/Users/romanzelenka/barmagazine-next/outreach/batch20-americas-send.log"
cd "$REPO" || exit 1
echo "=== batch20-americas w2 live send $(date) ===" >> "$LOG"

# RETRY ON FAILURE: three attempts, then 10 minutes, then 30.
#
# WHY. Supabase went down on 2026-09-21 and took a dry run with it. A send
# that dies partway is not a batch that mostly worked: the window closes, the
# one-shot deletes itself, and the unsent remainder is simply lost until
# somebody notices.
#
# An outage is indistinguishable from a bad list at the point of failure.
# send-upsell.mjs runs a pre-flight that counts every slug it cannot resolve
# as "no email on file", and an unreachable Supabase fails to resolve ALL of
# them, so the script exits 2 saying the list is malformed when the list is
# fine. That is why ANY non-zero exit is retried and not just a crash.
#
# RETRIES ARE SAFE BECAUSE OF THE SENT LOG. send-upsell.mjs appends each bar
# to outreach/sent-log.txt the moment its mail is accepted, and skips on the
# next run anything already in it. So attempt 2 mails only what attempt 1 did
# not reach, and a fully successful batch re-run exits 0 having sent nothing.
# Without that guard this loop would be a way to mail people three times.
BACKOFF=(0 600 1800)
STATUS=1
for ATTEMPT in 0 1 2; do
  if [ "${BACKOFF[$ATTEMPT]}" -gt 0 ]; then
    echo "=== batch20-americas w2 attempt $((ATTEMPT + 1)) waiting ${BACKOFF[$ATTEMPT]}s $(date) ===" >> "$LOG"
    sleep "${BACKOFF[$ATTEMPT]}"
  fi
  echo "=== batch20-americas w2 attempt $((ATTEMPT + 1)) start $(date) ===" >> "$LOG"
  /usr/local/bin/node scripts/send-upsell.mjs --send --batch batch20-americas --variant us $(cat outreach/batch20-americas-b.slugs) >> "$LOG" 2>&1
  STATUS=$?
  echo "=== batch20-americas w2 attempt $((ATTEMPT + 1)) exit $STATUS $(date) ===" >> "$LOG"
  [ "$STATUS" -eq 0 ] && break
done

if [ "$STATUS" -eq 0 ]; then
  echo "=== batch20-americas w2 done $(date) ===" >> "$LOG"
else
  echo "!!! batch20-americas w2 FAILED after 3 attempts, last exit $STATUS $(date)" >> "$LOG"
  echo "!!! Anything already mailed is in outreach/sent-log.txt; re-running the" >> "$LOG"
  echo "!!! same slug list sends only the remainder." >> "$LOG"
fi

# Clean up even after a total failure. A spent one-shot left armed with a past
# date fires again at the next login and sends unattended, which is the batch
# 14 w1 incident (2026-09-16). Delete first, then unload: the unload kills this
# job, so anything after it never runs.
rm -f "/Users/romanzelenka/Library/LaunchAgents/com.barmagazine.batch20-americas-w2.plist"
launchctl bootout gui/$(id -u)/com.barmagazine.batch20-americas-w2 >> "$LOG" 2>&1 || true
