#!/bin/bash
# One-shot runner for batch16-amer-eur window w3, armed 2026-09-17 for
# 2026-09-17 13:30 PT. Generated by outreach/arm-window.sh.
set -u
REPO="/Users/romanzelenka/barmagazine-next"
LOG="/Users/romanzelenka/barmagazine-next/outreach/batch16-amer-eur-send.log"
cd "$REPO" || exit 1
echo "=== batch16-amer-eur w3 live send $(date) ===" >> "$LOG"
/usr/local/bin/node scripts/send-upsell.mjs --send --batch batch16-amer-eur $(cat outreach/batch16-w3.slugs) >> "$LOG" 2>&1
echo "=== batch16-amer-eur w3 done $(date) ===" >> "$LOG"
# Delete first, then unload: the unload kills this job (batch 14 w1, 2026-09-16).
rm -f "/Users/romanzelenka/Library/LaunchAgents/com.barmagazine.batch16-amer-eur-w3.plist"
launchctl bootout gui/$(id -u)/com.barmagazine.batch16-amer-eur-w3 >> "$LOG" 2>&1 || true
