'use client';

/**
 * Seven rows, one per day. No free-text hours field.
 *
 * WHY. Owners typed hours in whatever shape they liked, because we asked them
 * to type. Prophecy sent "Sunday to Thursday, 4:00pm to 1:00am Friday &
 * Saturday, 4:00pm to 2:00am", which matches nothing else in the directory.
 * An owner cannot type a dash here because there is nowhere to type one, and
 * the display string is generated by us from what they pick.
 *
 * Past midnight is the normal case for a bar, not an error: a close time at or
 * before the open time is read as the next day and the row says so.
 *
 * Mobile is the constraint that shaped the layout. Seven rows of two time
 * inputs and a toggle is a lot on a phone, so the row is a grid that collapses
 * to the day label plus the two inputs side by side, and "Closed" is a
 * checkbox rather than a third control competing for width.
 */
import {
  DAYS, type Day, type StructuredHours, type DayHours,
  generateHoursString, runsPastMidnight, emptyWeek,
} from '@/lib/structured-hours';

const LABEL: Record<Day, string> = {
  mon: 'Monday', tue: 'Tuesday', wed: 'Wednesday', thu: 'Thursday',
  fri: 'Friday', sat: 'Saturday', sun: 'Sunday',
};
const SHORT: Record<Day, string> = {
  mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun',
};

export function HoursInput({
  value, onChange, name = 'opening_hours_structured',
}: {
  value?: StructuredHours;
  onChange: (next: StructuredHours) => void;
  /** Hidden field name, so the form posts the structure as JSON. */
  name?: string;
}) {
  const week = value || emptyWeek();

  const set = (day: Day, patch: Partial<DayHours>) => {
    onChange({ ...week, [day]: { ...week[day], ...patch } });
  };

  const copyMondayDown = () => {
    const mon = week.mon;
    const next = { ...week };
    for (const d of DAYS) next[d] = { ...mon };
    onChange(next);
  };

  const preview = generateHoursString(week);

  return (
    <div className="hours-input">
      <div className="hours-input-head">
        <span className="form-hint" style={{ margin: 0 }}>
          Pick the times. We format them the same way for every bar, so there is nothing to type.
        </span>
        <button type="button" className="hours-copy-btn" onClick={copyMondayDown}>
          Copy Monday to every day
        </button>
      </div>

      {DAYS.map(d => {
        const v = week[d];
        const past = runsPastMidnight(v);
        return (
          <div key={d} className={`hours-row${v.closed ? ' hours-row--closed' : ''}`}>
            <span className="hours-day">
              <span className="hours-day-long">{LABEL[d]}</span>
              <span className="hours-day-short">{SHORT[d]}</span>
            </span>

            {v.closed ? (
              <span className="hours-closed-note">Closed</span>
            ) : (
              <span className="hours-times">
                <input
                  type="time"
                  aria-label={`${LABEL[d]} opening time`}
                  value={v.open || ''}
                  onChange={e => set(d, { open: e.target.value })}
                  className="form-input hours-time"
                />
                <span className="hours-to">to</span>
                <input
                  type="time"
                  aria-label={`${LABEL[d]} closing time`}
                  value={v.close || ''}
                  onChange={e => set(d, { close: e.target.value })}
                  className="form-input hours-time"
                />
                {past && <span className="hours-next-day">next day</span>}
              </span>
            )}

            <label className="hours-closed-toggle">
              <input
                type="checkbox"
                checked={v.closed}
                onChange={e => set(d, { closed: e.target.checked })}
              />
              <span>Closed</span>
            </label>
          </div>
        );
      })}

      {preview && (
        <p className="hours-preview">
          <strong>Will show as:</strong> {preview}
        </p>
      )}

      {/* What actually posts. The string is generated on the server too, so a
          tampered field cannot put arbitrary text on a profile. */}
      <input type="hidden" name={name} value={JSON.stringify(week)} />
    </div>
  );
}
